baseurl: "https://movietalks.github.io"
title: "МувиТокс"
footnotereturnlinkcontents: "↩"
contentdir: "content"
layoutdir: "layout"
staticdir: "static"
publishdir: "docs"
pagination:
  pagerSize: 50
uglyURLs: false
metaDataFormat: "yaml"
LanguageCode: ru
params:
  itunes: https://podcasts.apple.com/podcast/id1616411400
  android: https://music.youtube.com/@movietalkspodcast
  feed: /index.xml
  yandex: https://music.yandex.ru/album/24067611
  desc: Подкаст о кино, в котором ничего не понятно
  summary: Странное кино с налетом гениальности, которое обсуждают ведущие с зубным налетом
  StaticURL: "https://movietalks.ru"
  LanguageCode: ru
  yandexS3: "https://storage.yandexcloud.net/movietalks/"
permalinks:
  post: "/:title"
